Repository theopenconversationkit/tock, pull requests merged in 2020-07, with the labels that each got.

#986 resolves #981 Tock Studio: improve Story-Rules display for long names
  bot/admin/web/src/app/bot/bot.module.ts
  bot/admin/web/src/app/bot/feature/story-rule.component.css
  bot/admin/web/src/app/bot/feature/story-rule.component.html
Labels: enhancement

#992 991 fix features display (refresh pb + layout)
  bot/admin/web/src/app/bot/feature/application-feature.component.css
  bot/admin/web/src/app/bot/feature/application-feature.component.html
  bot/admin/web/src/app/bot/feature/application-feature.component.ts
  bot/admin/web/src/app/bot/story/search-story.component.ts
Labels: bug, enhancement

#995 Flow minor improvements
  bot/admin/web/src/app/analytics/flow/flow.component.html
  bot/admin/web/src/app/analytics/flow/flow.component.ts
  bot/engine/src/main/kotlin/admin/dialog/DialogFlowStateData.kt
  bot/engine/src/main/kotlin/engine/dialog/Snapshot.kt
  bot/storage-mongo/src/main/kotlin/DialogFlowMongoDAO.kt
  bot/storage-mongo/src/main/kotlin/DialogFlowStateCol.kt
Labels: enhancement

#1004 fixes #931 prevent mediacard with only actions
  bot/admin/web/src/app/bot/story/media/media-dialog.component.html
  bot/admin/web/src/app/bot/story/media/media-dialog.component.ts
Labels: bug

#1011 resolves #1010 Open conversation view in new tab
  nlp/admin/web/src/app/sentence-analysis/highlight/highlight.component.html
Labels: enhancement
