Repository theopenconversationkit/tock, pull requests merged in 2024-07, with the labels that each got.

#1664 fix #1662 Bot Api: add standard way to change user locale from BotBus
  bot/engine/src/main/kotlin/engine/BotBus.kt
  bot/engine/src/main/kotlin/engine/TockBotBus.kt
  bot/engine/src/test/kotlin/engine/BotBusTest.kt
  bot/test-base/src/main/kotlin/BotBusMock.kt
Labels: enhancement

#1659 fix #1658 translator: fix answer update from admin resetting defaultI18n
  bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
  bot/admin/server/src/main/kotlin/model/BotI18nLabelUpdate.kt
  bot/storage-mongo/src/main/kotlin/I18nMongoDAO.kt
  docs/_en/dev/i18n.md
  docs/_fr/dev/i18n.md
  translator/core/src/main/kotlin/I18nDAO.kt
  translator/core/src/main/kotlin/I18nLabel.kt
  translator/core/src/main/kotlin/I18nLabelContract.kt
  translator/core/src/main/kotlin/I18nLabelValue.kt
  translator/core/src/main/kotlin/Translator.kt
Labels: bug

#1669 Messenger api version update
  bot/connector-messenger/src/main/kotlin/MessengerClient.kt
Labels: bug, enhancement

#1652 [DERCBOT-1060] Delete obsolete FAQ roles
  bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
  bot/admin/server/src/main/kotlin/verticle/IndicatorVerticle.kt
  bot/admin/test/core/src/main/kotlin/TestCoreService.kt
  docs/_fr/admin/securite.md
  docs/_fr/user/studio/faq-training.md
  nlp/admin/server/src/main/kotlin/AdminVerticle.kt
  shared/src/main/kotlin/security/TockUserRole.kt
  shared/src/main/kotlin/security/auth/PropertyBasedAuthProvider.kt
  shared/src/main/kotlin/vertx/WebVerticle.kt
Labels: enhancement

#1679 [WhatsApp Cloud] Add corrections to message list whastapp
  bot/connector-whatsapp-cloud/src/main/kotlin/WebhookActionConverter.kt
  bot/connector-whatsapp-cloud/src/main/kotlin/WhatsAppCloudApiClient.kt
  bot/connector-whatsapp-cloud/src/main/kotlin/WhatsAppCloudApiClientRepository.kt
  bot/connector-whatsapp-cloud/src/main/kotlin/database/repository/PayloadWhatsAppCloudMongoDAO.kt
Labels: bug

#1681 [Tock Studio - Hot fix] fix observability templates typing
  bot/admin/web/src/app/configuration/observability-settings/observability-provider-config-param-input/observability-provider-config-param-input.component.html
  bot/admin/web/src/app/configuration/observability-settings/observability-settings.component.html
Labels: bug

#1685 Move deprecated faq role mapping to TockUser init.
  shared/src/main/kotlin/security/TockUser.kt
  shared/src/main/kotlin/vertx/WebVerticle.kt
Labels: bug

#1686 [DERCBOT-1041] Normalise the namespace name of the connector's relative REST path
  bot/admin/web/src/app/core/bot-configuration.service.ts
  bot/connector-rest/src/main/kotlin/RestConnectorBuilder.kt
Labels: bug

#1698 [Tock studio] Test view : Refresh sentences when changing bot/namespace
  bot/admin/web/src/app/test/dialog/bot-dialog.component.ts
Labels: bug
