Repository theopenconversationkit/tock, pull requests merged in 2025-01, with the labels that each got.

#1767 [DERCBOT-1173] RAG Evaluation - Langfuse
  .gitignore
  gen-ai/orchestrator-server/src/main/python/server/poetry.lock
  gen-ai/orchestrator-server/src/main/python/server/pyproject.toml
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/configurations/environment/settings.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/llm/azure_openai_llm_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/llm/llm_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/llm/openai_llm_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/vector_stores/open_search_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/vector_stores/pgvector_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/vector_stores/vector_store_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/.env
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/README.md
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/docs/rag_testing_tools.png
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/.exemple.env
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/rag_query.example.json
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/export_run_results.py
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/poetry.lock
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/pyproject.toml
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/rag_testing_tool.py
Labels: enhancement

#1793 [GEN AI] Improving Langfuse's traces
  bot/engine/src/main/kotlin/engine/action/ActionMetadata.kt
  bot/engine/src/main/kotlin/engine/config/RAGAnswerHandler.kt
  bot/storage-mongo/target/generated-sources/kapt/compile/ai/tock/bot/engine/action/ActionMetadata_.kt
  gen-ai/orchestrator-client/src/main/kotlin/ai/tock/genai/orchestratorclient/requests/RAGQuery.kt
  gen-ai/orchestrator-client/src/main/kotlin/ai/tock/genai/orchestratorclient/responses/RAGResponse.kt
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/rag/rag_models.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/requests/requests.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/responses/responses.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/completion/completion_service.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/langchain_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
  gen-ai/orchestrator-server/src/main/python/server/tests/services/test_rag_chain.py
Labels: enhancement

#1798 [Tock Studio] Add the ability to open a single dialog in a view with url
  bot/admin/web/src/app/analytics/analytics-routing.module.ts
  bot/admin/web/src/app/analytics/analytics.module.ts
  bot/admin/web/src/app/analytics/analytics.service.ts
  bot/admin/web/src/app/analytics/dialog/dialog.component.html
  bot/admin/web/src/app/analytics/dialog/dialog.component.scss
  bot/admin/web/src/app/analytics/dialog/dialog.component.spec.ts
  bot/admin/web/src/app/analytics/dialog/dialog.component.ts
  bot/admin/web/src/app/analytics/dialogs/dialogs-list/dialogs-list.component.html
  bot/admin/web/src/app/analytics/dialogs/dialogs-list/dialogs-list.component.ts
  bot/admin/web/src/app/analytics/dialogs/dialogs.component.html
  bot/admin/web/src/app/analytics/users/users.component.html
  bot/admin/web/src/app/faq/faq-management/faq-management.component.ts
  bot/admin/web/src/app/shared/bot-shared.module.ts
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-dialog-logger/chat-ui-dialog-logger.component.html
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-dialog-logger/chat-ui-dialog-logger.component.scss
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-dialog-logger/chat-ui-dialog-logger.component.spec.ts
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-dialog-logger/chat-ui-dialog-logger.component.ts
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-message/chat-ui-message-sentence-element/chat-ui-message-sentence-element.component.html
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-message/chat-ui-message-sentence-footnotes/chat-ui-message-sentence-footnotes.component.html
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-message/chat-ui-message.component.html
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-message/chat-ui-message.component.scss
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui-message/chat-ui-message.component.ts
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui.component.html
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui.component.scss
  bot/admin/web/src/app/shared/components/chat-ui/chat-ui.component.ts
  bot/admin/web/src/app/shared/components/form-control/form-control.component.html
  bot/admin/web/src/app/shared/components/form-control/form-control.component.ts
  bot/admin/web/src/app/shared/components/index.ts
  bot/admin/web/src/app/shared/components/report/report.component.html
  bot/admin/web/src/app/shared/components/report/report.component.scss
  bot/admin/web/src/app/shared/components/report/report.component.spec.ts
  bot/admin/web/src/app/shared/components/report/report.component.ts
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training-dialog/sentence-training-dialog.component.html
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training-dialog/sentence-training-dialog.component.ts
  bot/admin/web/src/app/shared/components/test-dialog/test-dialog.component.html
  bot/admin/web/src/app/shared/model/dialog-data.ts
  bot/admin/web/src/app/test/dialog/bot-dialog.component.html
  bot/admin/web/src/app/test/model/test.ts
  bot/admin/web/src/app/test/plan/test-plan.component.ts
  bot/admin/web/src/app/theme/styles/utilities.scss
Labels: enhancement

#1802 [DERCBOT-1249] Search a single dialog
  bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
  bot/storage-mongo/src/main/kotlin/UserTimelineMongoDAO.kt
Labels: bug

#1800 [DERCBOT-1281] Improving NLP result details
  bot/admin/web/src/app/applications/application/application.component.html
  bot/admin/web/src/app/applications/application/application.component.ts
  bot/admin/web/src/app/configuration/bot-configurations/new-bot.component.ts
  bot/admin/web/src/app/model/application.ts
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training-entry/sentence-training-entry.component.html
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training-entry/sentence-training-entry.component.ts
  nlp/admin/server/src/main/kotlin/model/ApplicationWithIntents.kt
  nlp/front/service/src/main/kotlin/ParserService.kt
  nlp/front/service/src/main/kotlin/selector/DefaultIntentSelector.kt
  nlp/front/service/src/main/kotlin/selector/ExpectedIntentSelector.kt
  nlp/front/shared/src/main/kotlin/config/ApplicationDefinition.kt
Labels: bug, enhancement

#1805 [Tock Studio] Fix answer label namespace case
  bot/admin/web/src/app/bot/story/answer/simple-answer/simple-answer.component.ts
Labels: bug

#1807 [Tock Studio] Optional deepening strategy on data export component
  bot/admin/web/src/app/faq/faq-management/faq-management.component.html
  bot/admin/web/src/app/faq/faq-management/faq-management.component.ts
  bot/admin/web/src/app/shared/components/data-export/data-export.component.ts
  bot/admin/web/src/app/shared/utils/utils.ts
Labels: enhancement

#1809 [Tock Studio] Sentence training UX improvements
  bot/admin/web/src/app/shared/components/sentence-training/sentence-review-request/sentence-review-request.component.html
  bot/admin/web/src/app/shared/components/sentence-training/sentence-review-request/sentence-review-request.component.ts
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training-entry/sentence-training-entry.component.html
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training-entry/sentence-training-entry.component.ts
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training.component.html
  bot/admin/web/src/app/shared/components/sentence-training/sentence-training.component.ts
Labels: enhancement

#1820 [DERCBOT-1327] Git hooks - Gitleaks
  .pre-commit-config.yaml
  README.md
  gen-ai/orchestrator-core/src/main/kotlin/ai/tock/genai/orchestratorcore/utils/SecurityUtils.kt
  gen-ai/orchestrator-server/src/main/python/server/.pre-commit-config.yaml
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/em/azureopenai/azure_openai_em_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/em/em_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/em/openai/openai_em_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/llm/azureopenai/azure_openai_llm_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/llm/llm_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/llm/openai/openai_llm_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/observability/langfuse/langfuse_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/security/raw_secret_key/raw_secret_key.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/vector_stores/open_search/open_search_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/vector_stores/pgvector/pgvector_setting.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/em_providers_router.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/llm_providers_router.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/observability_providers_router.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/requests/requests.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/vector_store_providers_router.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/langchain_factory.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/security/security_service.py
  gen-ai/orchestrator-server/src/main/python/server/tests/routers/test_completion_router.py
  gen-ai/orchestrator-server/src/main/python/server/tests/services/test_langchain_factory.py
  gen-ai/orchestrator-server/src/main/python/server/tests/services/test_qa_chain.py
  gen-ai/orchestrator-server/src/main/python/server/tests/services/test_rag_chain.py
  gen-ai/orchestrator-server/src/main/python/server/tests/services/test_security_service.py
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/embeddings_azure_openai_settings.example.json
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/embeddings_openai_settings.example.json
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/rag_query.example.json
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/vector_store_opensearch_settings.example.json
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/vector_store_pgvector_settings.example.json
  shared/src/main/kotlin/security/key/RawSecretKey.kt
Labels: enhancement

#1825 Increase test dialog modal max height
  bot/admin/web/src/app/shared/components/test-dialog/test-dialog.component.html
Labels: enhancement

#1814 [DERCBOT-1314] Add documentsRequired Setting to BotRAGConfiguration
  bot/admin/server/src/main/kotlin/model/BotRAGConfigurationDTO.kt
  bot/engine/src/main/kotlin/admin/bot/rag/BotRAGConfiguration.kt
  bot/engine/src/main/kotlin/engine/config/RAGAnswerHandler.kt
  gen-ai/orchestrator-client/src/main/kotlin/ai/tock/genai/orchestratorclient/requests/RAGQuery.kt
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/routers/requests/requests.py
  gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
  gen-ai/orchestrator-server/src/main/python/server/tests/services/test_qa_chain.py
  gen-ai/orchestrator-server/src/main/python/server/tests/services/test_rag_chain.py
Labels: enhancement

#1803 [DERCBOT-1283] Generate dataset - New Excel template
  .gitignore
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/README.md
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/examples/generate_dataset_input.example.xlsx
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/export_run_results.py
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset_input.xlsx
  gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/models.py
Labels: enhancement
